# Generated by Django 2.1.7 on 2019-08-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gitnoti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('repo_name', models.CharField(max_length=100)),
                ('repo_url', models.CharField(max_length=100)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_url', models.CharField(max_length=100)),
            ],
        ),
    ]
